analyzer:
  errors:
    duplicate_import: ignore
    must_be_immutable: ignore
    unnecessary_cast: ignore
    undefined_class: ignore
    undefined_identifier: ignore
    type_test_with_undefined_name: ignore
